In [1]:
import sys
from pathlib import Path

# make the project root importable when the notebook runs from notebooks/
ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

In [ ]:
from src.data.data_loader import DataLoader

loader = DataLoader()
call_data = loader.load_parquet("../data/spx_option_chain.parquet")
price_data = loader.load_parquet("../data/spx_price.parquet")

In [15]:
call_data = call_data[(call_data.bid != 0) & (call_data.ask != 0)]
call_data["Price"] = (call_data.bid + call_data.ask) / 2

In [16]:
call_data

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency,expiry,type,Price
0,SPXW260608C04600000,1970-01-01 00:29:40.680000+00:00,4600.0,2854.81,2842.3,2862.7,0.0,0.0,4.0,4,6.396181,True,REGULAR,USD,2026-06-08,call,2852.50
1,SPXW260608C04800000,1970-01-01 00:29:40.666000+00:00,4800.0,2731.20,2642.3,2662.7,0.0,0.0,1.0,1,5.923648,True,REGULAR,USD,2026-06-08,call,2652.50
2,SPXW260608C05200000,1970-01-01 00:29:40.676000+00:00,5200.0,2263.77,2242.3,2261.2,0.0,0.0,17.0,9,5.011478,True,REGULAR,USD,2026-06-08,call,2251.75
3,SPXW260608C05400000,1970-01-01 00:29:40.674000+00:00,5400.0,2080.73,2039.8,2060.5,0.0,0.0,1.0,1,4.554448,True,REGULAR,USD,2026-06-08,call,2050.15
4,SPXW260608C05600000,1970-01-01 00:29:40.674000+00:00,5600.0,1882.13,1841.1,1861.6,0.0,0.0,4.0,3,4.159123,True,REGULAR,USD,2026-06-08,call,1851.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1979,SPXW260612P07900000,1970-01-01 00:29:40.680000+00:00,7900.0,441.60,432.6,452.6,0.0,0.0,7.0,20,0.000010,True,REGULAR,USD,2026-06-12,put,442.60
1980,SPXW260612P08100000,1970-01-01 00:29:40.595000+00:00,8100.0,503.94,632.5,652.7,0.0,0.0,4.0,7,0.000010,True,REGULAR,USD,2026-06-12,put,642.60
1981,SPXW260612P08125000,1970-01-01 00:29:40.595000+00:00,8125.0,528.26,659.2,676.8,0.0,0.0,NaN,4,0.000010,True,REGULAR,USD,2026-06-12,put,668.00
1982,SPXW260612P08200000,1970-01-01 00:29:39.130000+00:00,8200.0,824.83,732.1,752.7,0.0,0.0,1.0,0,0.000010,True,REGULAR,USD,2026-06-12,put,742.40
1983,SPXW260612P09800000,1970-01-01 00:29:40.685000+00:00,9800.0,2387.86,2332.9,2351.6,0.0,0.0,5.0,5,0.000010,True,REGULAR,USD,2026-06-12,put,2342.25

In [10]:
s0 = price_data["('Close', '^SPX')"].iloc[0]
s0

np.float64(2012.6600341796875)

In [ ]:
k = call_data[call_data.type == "call"]["strike"].to_numpy()
r = 0.05

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency,expiry,type
212,SPXW260608P03000000,1970-01-01 00:29:40.678000+00:00,3000.0,0.05,0.0,0.0,0.0,0.0,2.0,10,0.500005,False,REGULAR,USD,2026-06-08,put
213,SPXW260608P03200000,1970-01-01 00:29:38.868000+00:00,3200.0,0.10,0.0,0.0,0.0,0.0,6.0,6,0.500005,False,REGULAR,USD,2026-06-08,put
214,SPXW260608P03400000,1970-01-01 00:29:40.689000+00:00,3400.0,0.05,0.0,0.0,0.0,0.0,1.0,136,0.500005,False,REGULAR,USD,2026-06-08,put
215,SPXW260608P03600000,1970-01-01 00:29:39.122000+00:00,3600.0,0.10,0.0,0.0,0.0,0.0,10.0,32,0.500005,False,REGULAR,USD,2026-06-08,put
216,SPXW260608P03800000,1970-01-01 00:29:38.789000+00:00,3800.0,0.10,0.0,0.0,0.0,0.0,1.0,218,0.500005,False,REGULAR,USD,2026-06-08,put
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1979,SPXW260612P07900000,1970-01-01 00:29:40.680000+00:00,7900.0,441.60,432.6,452.6,0.0,0.0,7.0,20,0.000010,True,REGULAR,USD,2026-06-12,put
1980,SPXW260612P08100000,1970-01-01 00:29:40.595000+00:00,8100.0,503.94,632.5,652.7,0.0,0.0,4.0,7,0.000010,True,REGULAR,USD,2026-06-12,put
1981,SPXW260612P08125000,1970-01-01 00:29:40.595000+00:00,8125.0,528.26,659.2,676.8,0.0,0.0,NaN,4,0.000010,True,REGULAR,USD,2026-06-12,put
1982,SPXW260612P08200000,1970-01-01 00:29:39.130000+00:00,8200.0,824.83,732.1,752.7,0.0,0.0,1.0,0,0.000010,True,REGULAR,USD,2026-06-12,put
1983,SPXW260612P09800000,1970-01-01 00:29:40.685000+00:00,9800.0,2387.86,2332.9,2351.6,0.0,0.0,5.0,5,0.000010,True,REGULAR,USD,2026-06-12,put

In [ ]:
call_data.expiry

AttributeError: 'DataFrame' object has no attribute 'valuation_date'

In [ ]:
from src.algorithms.heston.heston_analytics import HestonModel
from src.algorithms.heston.heston_params import HestonParams

initial_params = HestonParams(.5, .5, 10.0, 2.5, .5)
model = HestonModel(init_params=initial_params)
model.optimize_params()

TypeError: HestonModel.optimize_params() missing 5 required positional arguments: 'k', 's_0', 'r', 't', and 'call'